Repository ucsb-cs156-s24/proj-gauchoride-s24-5pm-6, pull requests merged in 2024-05, with the labels that each got.

#18 Fixed the Labels for Time
  frontend/src/main/components/Ride/RideForm.js
Labels: Ready for Staff Review, 5

#19 Fixed the Headers for Shift Table
  frontend/src/main/components/Shift/ShiftTable.js
  frontend/src/tests/components/Shift/ShiftTable.test.js
Labels: Ready for Staff Review

#33 Diya - fix labels for drivers form
  frontend/src/main/components/Driver/DriverAvailabilityForm.js
  frontend/src/tests/components/Driver/DriverAvailabilityForm.test.js
  frontend/src/tests/pages/Drivers/DriverAvailabilityCreatePage.test.js
Labels: 5

#22 Lindsey - fixed bug (404 error) on Apply to be a Rider button
  frontend/src/fixtures/currentUserFixtures.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
Labels: 5

#28 Diya new driver index page
  frontend/src/main/components/Driver/DriverAvailabilityTable.js
  frontend/src/main/pages/DriverInfoPage.js
  frontend/src/tests/components/Driver/DriverAvailabilityTable.test.js
  frontend/src/tests/pages/DriverInfoPage.test.js
Labels: 5

#20 Anika - Non-Admin Users CanNOT Access Driver List
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriversController.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/DriversControllerTests.java
Labels: Ready for Staff Review

#24 Yuji RiderNavBar Updates
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
Labels: 5

#29 Diya - fix driver date inconsistency
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityControllerTests.java
Labels: Ready for Staff Review

#34 Lindsey - Automatically toggle rider role after accepting application feature
  frontend/src/main/components/RiderApplication/RiderApplicationEditForm.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/components/RiderApplication/RiderApplicationEditForm.test.js
Labels: Ready for Staff Review

#36 Diya - Updating Driver Availability Form Frontend with error messages and placeholder values
  frontend/src/main/components/Driver/DriverAvailabilityForm.js
  frontend/src/tests/components/Driver/DriverAvailabilityForm.test.js
Labels: 5

#35 Yuji - Dropdown for DriverID in create shifts
  frontend/src/main/components/Shift/ShiftForm.js
  frontend/src/tests/components/Shift/ShiftForm.test.js
  frontend/src/tests/pages/Shift/ShiftCreatePage.test.js
  frontend/src/tests/pages/Shift/ShiftEditPage.test.js
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/ShiftController.java
Labels: Ready for Staff Review

#26 liz - sort users table by default
  frontend/src/fixtures/usersFixtures.js
  frontend/src/main/components/Users/UsersTable.js
  frontend/src/tests/components/Users/UsersTable.test.js
  frontend/src/tests/pages/AdminUsersPage.test.js
Labels: 10

#37 Yuji - Update Backend code to Spring 3
  .github/workflows/13-backend-incremental-pitest.yml
  .github/workflows/14-backend-pitest.yml
  pom.xml
  src/main/java/edu/ucsb/cs156/gauchoride/aop/LoggingAspect.java
  src/main/java/edu/ucsb/cs156/gauchoride/config/SecurityConfig.java
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/ApiController.java
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityController.java
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/RideController.java
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationController.java
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/ShiftController.java
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/UserInfoController.java
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/UserProfileController.java
  src/main/java/edu/ucsb/cs156/gauchoride/entities/ChatMessage.java
  src/main/java/edu/ucsb/cs156/gauchoride/entities/DriverAvailability.java
  src/main/java/edu/ucsb/cs156/gauchoride/entities/Ride.java
  src/main/java/edu/ucsb/cs156/gauchoride/entities/RiderApplication.java
  src/main/java/edu/ucsb/cs156/gauchoride/entities/Shift.java
  src/main/java/edu/ucsb/cs156/gauchoride/entities/User.java
  src/main/java/edu/ucsb/cs156/gauchoride/interceptors/RoleInterceptor.java
  src/main/resources/application-production.properties
  src/test/java/edu/ucsb/cs156/gauchoride/config/SecurityConfigTests.java
  src/test/java/edu/ucsb/cs156/gauchoride/services/CurrentUserServiceTests.java
  src/test/java/edu/ucsb/cs156/gauchoride/services/GrantedAuthoritiesServiceTests.java
  src/test/java/edu/ucsb/cs156/gauchoride/testconfig/TestConfig.java
Labels: Ready for Staff Review

#39 Wesley - Expose commit info
  Dockerfile
  frontend/src/fixtures/systemInfoFixtures.js
  frontend/src/main/utils/systemInfo.js
  frontend/src/tests/utils/systemInfo.test.js
  pom.xml
  src/main/java/edu/ucsb/cs156/gauchoride/models/SystemInfo.java
  src/main/java/edu/ucsb/cs156/gauchoride/services/SystemInfoServiceImpl.java
  src/test/java/edu/ucsb/cs156/gauchoride/services/SystemInfoServiceImplTests.java
Labels: Ready for Staff Review

#40 Lindsey - Fixed rider application bug
  frontend/src/main/pages/RiderApplication/RiderApplicationEditPageAdmin.js
  frontend/src/main/pages/RiderApplication/RiderApplicationIndexPageAdmin.js
  frontend/src/tests/pages/RiderApplication/RiderApplicationEditPageAdmin.test.js
  frontend/src/tests/pages/RiderApplication/RiderApplicationIndexPageAdmin.test.js
Labels: Ready for Staff Review

#50 Yuji - Different Drivers for Create Shift
  frontend/src/main/components/Shift/ShiftForm.js
  frontend/src/tests/components/Shift/ShiftForm.test.js
Labels: Ready for Staff Review

#52 Yuji - Driver Availability End Time has to be later than Start Time
  frontend/package-lock.json
  frontend/package.json
  frontend/src/main/components/Driver/DriverAvailabilityForm.js
  frontend/src/tests/components/Driver/DriverAvailabilityForm.test.js
Labels: Ready for Staff Review
