Repository ucsb-cs156-s24/proj-gauchoride-s24-5pm-6, pull requests merged in 2024-06, with the labels that each got.

#43 liz - swagger navbar environment variable
  src/main/resources/application-development.properties
  src/main/resources/application-production.properties
Labels: Ready for Staff Review

#46 liz - h2 console navbar environment variable
  src/main/resources/application-development.properties
  src/main/resources/application-production.properties
Labels: Ready for Staff Review

#57 Wesley - Make systemInfo available when not logged in
  README.md
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/SystemInfoController.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/SystemInfoControllerTests.java
Labels: Ready for Staff Review

#51 Yuji - Create Shift End Time has to be later than Start Time
  frontend/src/main/components/Shift/ShiftForm.js
  frontend/src/tests/components/Shift/ShiftForm.test.js
Labels: Ready for Staff Review

#56 Wesley - FIX Github repo link being hardcoded
  frontend/src/fixtures/systemInfoFixtures.js
  frontend/src/main/components/Nav/Footer.js
  frontend/src/tests/components/Nav/Footer.test.js
Labels: 10

#54 Lindsey - Driver Availability Backend + Corresponding Frontend Changes
  frontend/src/main/components/Driver/DriverAvailabilityForm.js
  frontend/src/tests/components/Driver/DriverAvailabilityForm.test.js
  frontend/src/tests/pages/Drivers/DriverAvailabilityCreatePage.test.js
  frontend/src/tests/pages/Drivers/DriverAvailabilityEditPage.test.js
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityController.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityControllerTests.java
Labels: Ready for Staff Review, 10

#58 Anika Ride Request Assign Driver
  frontend/src/fixtures/shiftFixturesSecond.js
  frontend/src/main/components/Ride/RideAssignDriverForm.js
  frontend/src/tests/components/Ride/RideAssignDriverForm.test.js
  frontend/src/tests/pages/Ride/RideRequestAssignPage.test.js
Labels: Ready for Staff Review, 10
